cleanupUnusedCatalogs: true

shellEmulator: true

trustPolicy: no-downgrade

packages:
  - packages/*

catalogs:
  dev:
    '@vue/tsconfig': ^0.8.1
    bumpp: ^10.3.2
    tailwindcss: ^3.4.17
    tsdown: ^0.20.1
    typescript: ~5.9.3
    unocss: ^66.5.10

onlyBuiltDependencies:
  - esbuild
