/**
 * 生成 Tailwind CSS v4 兼容主题 CSS 文件（compat.css）
 *
 * 读取 src/v4.ts 中的 generateCompatThemeCSS() 输出，写入到包根 compat.css。
 *
 * 运行方式：
 *   pnpm generate:compat
 */

import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { generateCompatThemeCSS } from '../src/v4.ts'

const __dirname = dirname(fileURLToPath(import.meta.url))

const FILE_HEADER = `/**
 * Ant Design Vue Tailwind CSS v4 Compatibility Theme
 *
 * 命名空间安全的 v4 入口 —— 所有 token 都以 \`ant-\` 命名空间隔离，
 * 不会与 Tailwind 内置 token 或项目自定义 token 冲突。
 *
 * 使用方法：
 *
 *   @import "tailwindcss";
 *   @import "@antdv-next/tailwind/compat.css";
 *
 * 然后可以使用：
 *   <div class="bg-ant-primary text-ant-lg rounded-ant-lg p-ant-lg shadow-ant-card">
 *     namespace-safe
 *   </div>
 *
 *   <div class="a-bg-primary a-text-lg a-rounded-lg a-p-lg a-shadow-card">
 *     prefixed shortcut
 *   </div>
 *
 * 此文件由 scripts/generate-compat.ts 自动生成，请勿手动修改。
 * This file is auto-generated by scripts/generate-compat.ts, do not edit manually.
 */

`

const css = FILE_HEADER + generateCompatThemeCSS()

const outputPath = resolve(__dirname, '../compat.css')
writeFileSync(outputPath, css, 'utf-8')

// eslint-disable-next-line no-console
console.log(`✅ compat.css generated → ${outputPath}`)
