/**
 * 生成 Tailwind CSS v4 主题 CSS 文件（theme.css）
 *
 * 此脚本读取 src/v4.ts 中的 generateThemeCSS() 生成内容
 * 并写入到包根目录的 theme.css 文件中。
 *
 * 运行方式：
 *   pnpm generate:theme
 */

import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { generateCompatThemeCSS, generateThemeCSS } from '../src/v4.ts'

const __dirname = dirname(fileURLToPath(import.meta.url))

const FILE_HEADER = `/**
 * Ant Design Vue Tailwind CSS v4 Theme
 *
 * 使用 @theme 指令定义主题变量，适用于 Tailwind CSS v4+
 *
 * 使用方法：
 * @import "tailwindcss";
 * @import "@antdv-next/tailwind/theme.css";
 *
 * 此文件由 scripts/generate-theme.ts 自动生成，请勿手动修改。
 * This file is auto-generated by scripts/generate-theme.ts, do not edit manually.
 */

`

const css = FILE_HEADER + generateThemeCSS()

const outputPath = resolve(__dirname, '../theme.css')
writeFileSync(outputPath, css, 'utf-8')

// eslint-disable-next-line no-console
console.log(`✅ theme.css generated → ${outputPath}`)

const COMPAT_FILE_HEADER = `/**
 * Ant Design Vue Tailwind CSS v4 Compat Theme
 *
 * 使用 namespace 隔离 Tailwind v4 theme token，适用于 Tailwind CSS v4+
 *
 * 使用方法：
 * @import "tailwindcss";
 * @import "@antdv-next/tailwind/compat.css";
 *
 * 此文件由 scripts/generate-theme.ts 自动生成，请勿手动修改。
 * This file is auto-generated by scripts/generate-theme.ts, do not edit manually.
 */

`

const compatCss = COMPAT_FILE_HEADER + generateCompatThemeCSS()

const compatOutputPath = resolve(__dirname, '../compat.css')
writeFileSync(compatOutputPath, compatCss, 'utf-8')

// eslint-disable-next-line no-console
console.log(`✅ compat.css generated → ${compatOutputPath}`)
